output_dir: ~/experiments/
load: None
rotate: ~/RotatE/models/RotatE_YAGO3-10_0/
complex: ~/SimKGC-main/data/YAGO3-10/ComplEx/
simkgc: ~/SimKGC-main/
ranklist_path: None
weight_path: None
train_model: yes

dataset:
  class: YAGO3-10
  root: ~/datasets/knowledge_graphs/YAGO3-10/raw/

model:
  class: NBFNet
  input_dim: 8
  hidden_dims: [8, 8, 8, 8, 8, 8]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  loss: margin
  init: 2.0
  need_nbf: no
  need_sim: yes
  need_rotate: yes
  need_complex: no
  method: ensemble
  rerank: forward
  ensemble_nbf: no
  ensemble_sim: no
  ensemble_atomic: yes
  ensemble_hidden_dim: 16
  div: yes
  get_feat: no

task:
  num_negative: 9999 # Changed
  strict_negative: yes
  adversarial_temperature: 4.0
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@100]

optimizer:
  class: Adam
  lr: 5.0e-5

train:
  gpus: {{ gpus }}
  batch_size: 4
  num_epoch: 1
  log_interval: 1
